name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

env:
  VGPU_SAMPLES: OFF

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Configure win-x64
      run: cmake -S . -B build_win_64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Release -DCMAKE_INSTALL_PREFIX="win-x64-sdk"

    - name: Build win-x64
      run: cmake --build build_win_64 --target install --config Release

    - name: Package Windows
      run: |
        mkdir bin/win-x64
        mv win-x64-sdk\bin\*.dll bin/win-x64

    - uses: actions/upload-artifact@v4
      with:
        name: libs_windows
        path: bin

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

    - name: Configure linux-x64
      run: cmake -S . -B build_linux_64 -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="linux-x64-sdk"

    - name: Build linux-x64
      run: cmake --build build_linux_64 --target install --config Release --verbose --parallel

    - name: Package Linux and Android
      run: |
        mkdir -p bin/linux-x64
        mv linux-x64-sdk/lib/*.so bin/linux-x64

    - uses: actions/upload-artifact@v4
      with:
        name: libs_linux
        path: bin

  macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Configure osx-universal
      run: cmake -S . -B build_osx -G Ninja -DCMAKE_BUILD_TYPE:String=Release -DCMAKE_INSTALL_PREFIX="osx-universal-sdk" -D"CMAKE_OSX_ARCHITECTURES=x86_64;arm64"

    - name: Build osx-universal
      run: cmake --build build_osx --target install --config Release --verbose --parallel

    - name: Package osx-universal
      run: |
        mkdir -p bin/osx-universal
        mv osx-universal-sdk/lib/*.dylib bin/osx-universal

    - uses: actions/upload-artifact@v4
      with:
        name: libs_osx
        path: bin

  combine:
    name: Combine artifacts
    runs-on: ubuntu-20.04
    needs:  [windows, linux, macos]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts

      - name: Combine
        run: |
          mkdir vgpu_libs
          cp -r artifacts/libs_windows/* vgpu_libs
          cp -r artifacts/libs_linux/* vgpu_libs
          cp -r artifacts/libs_osx/* vgpu_libs

      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z vgpu_libs.7z ./vgpu_libs/

      - uses: AButler/upload-release-assets@v2.0
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          files: vgpu_libs.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: 'Build Artifacts'
          path: vgpu_libs.7z
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            libs_windows
            libs_linux
            libs_osx
